-- Query 5
-- Find candidates who have enrolled in sessions but haven't paid the full fee
SELECT 
    C.CANDIDATE_CODE,
    C.CANDIDATE_FNAME,
    C.CANDIDATE_LNAME,
    S.SESSION_CODE,
    S.SESSION_START_DATE,
    S.SESSION_FEE,
    E.ENROLLMENT_FEE_PAYMENT,
    (S.SESSION_FEE - E.ENROLLMENT_FEE_PAYMENT) AS BALANCE,
    E.ENROLLMENT_DATE
FROM CANDIDATE AS C
INNER JOIN ENROLLMENT AS E ON C.CANDIDATE_CODE = E.CANDIDATE_CODE
INNER JOIN SESSION AS S ON E.SESSION_CODE = S.SESSION_CODE
WHERE 
    S.SESSION_START_DATE BETWEEN '2025-01-01' AND '2025-03-31'
    AND (
        E.ENROLLMENT_FEE_PAYMENT IS NULL OR
        E.ENROLLMENT_FEE_PAYMENT < S.SESSION_FEE
    )
ORDER BY 
    C.CANDIDATE_LNAME,
    C.CANDIDATE_FNAME;

-- Query 6
-- Count successful placements by company and job opening
SELECT 
    CO.COMPANY_NAME AS Company,
    JO.JOB_OPENING_DESCRIPTION AS Job_Opening,
    Q.QUALIFICATION_DESCRIPTION AS Required_Qualification,
    COUNT(P.CANDIDATE_CODE) AS Successful_Placements
FROM COMPANY AS CO
INNER JOIN JOB_OPENING AS JO 
    ON CO.COMPANY_CODE = JO.COMPANY_CODE
INNER JOIN QUALIFICATION AS Q 
    ON JO.QUALIFICATION_CODE = Q.QUALIFICATION_CODE
LEFT JOIN PLACEMENT AS P 
    ON JO.JOB_OPENING_CODE = P.JOB_OPENING_CODE
GROUP BY 
    CO.COMPANY_NAME, 
    JO.JOB_OPENING_DESCRIPTION, 
    Q.QUALIFICATION_DESCRIPTION
ORDER BY 
    CO.COMPANY_NAME, 
    JO.JOB_OPENING_DESCRIPTION;

